name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_order: base, habits, languages, isocalendar, lines
          plugin_habits: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
